name: Fifteenth Workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2 + 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: math-result-step-1
          path: math-result.txt

  interim-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: math-result-step-1
      - name: Math Expression
        run: |
          value=`cat math-result.txt`
          expr $value \* 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: math-result-step-2
          path: math-result.txt

  second-job:
    runs-on: ubuntu-latest
    needs: interim-job
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: math-result-step-2
      - name: Print File
        run: |
          value=`cat math-result.txt`
          echo $value
