name: Thirteenth Workflow
on: push

jobs:
  # failure() success() always() cancelled()
  job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: sleep 30
      - name: Runs on Cancelled
        if: ${{ cancelled() }}
        run: echo "Runs on Cancelled"
      - name: Runs always
        if: ${{ always() }}
        run: echo "Runs always"
      - name: Runs on Success
        if: ${{ success() }}
        run: echo "Runs on Failure"
      - name: Runs on Success
        if: ${{ failure() }}
        run: echo "Runs on Failure"