name: Thirteenth Workflow
on: push

jobs:
  # failure() success() always() cancelled()
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failure Step
        id: error-step
        run: exit 1
      - name: Runs on Cancelled
        if: ${{ cancelled() }}
        run: echo "Runs on Cancelled"
      - name: Runs always
        if: ${{ always() }}
        run: echo "Runs always"
      - name: Runs on Success
        if: ${{ success() }}
        run: echo "Runs on Success"
      - name: Runs on Failure
        if: ${{ failure() && steps.error-step.conclusion == 'failure' }}
        run: echo "Runs on Failure"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    if: ${{ failure() }}
    steps:
      - run: echo "Job failed"
