name: Third Workflow
on: push

jobs:
  list-files: 
   runs-on: ubuntu-latest
   steps:
    - name: List Files
      run: lols -a
    # - uses: actions/checkout@v4
    - name: Copy Files
      run: |
        git init
        git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
        git fetch origin
        git checkout main
    - name: List Files After Checkout
      run: ls -a