name: Twelfth Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "testing"
    steps:
      - name: Our Vars & Secrets
        run: |
          echo "${{ Vars.KEY }}"
          echo "${{ secrets.LOGIN }}"
